### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by squallliu** [achaphiv/ppa-fonts#25]
Please build both freetype and fontconfig-infinality for ubuntu 16.04.
thanks..

**Comment by mikhailnov** [comment]
freetpe is already built, but fontconfig-infinality is missing...
please build it, thank you in advance

**Comment by achaphiv** [comment]
Sorry for the late response.

I tried building freetype6 on Xenial and it [failed](https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa/+build/9315727).

I don't actually have a Xenial box, so it's hard to determine why it's failing. I should hopefully get this done before the official Xenial release (Apr 21?).

**Comment by mikhailnov** [comment]
Maybe because Ubuntu 16.04 doesn't think that SHA1 is not secure in some cases (I'm not aware enough of cryptography)? For example I get such errors while apt update:
W: http://dl.google.com/linux/webdesigner/deb/dists/stable/Release.gpg: Signature by key 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 uses weak digest algorithm (SHA1)
W: http://repo.yandex.ru/yandex-disk/deb/dists/stable/InRelease: Signature by key EE2C95AB58DC2B0138D16B4FEFC4571D7C90E5AF uses weak digest algorithm (SHA1)

**Comment by thuandt** [comment]
Thanks for your packages.
I has been used it more than year, but `fontconfig-infinality` config files is very old.
@achaphiv can you update latest font config files for this repos?

With new comming releases (16.04) I hope can continue use your packages.

Thanks for your works!

**Comment by greatquux** [comment]
It looks like bohoomil's patch for freetype 2.6.1 is no longer applying. Might be simpler just to import upstream freetype 2.6.2 and his current patches and just build like that.

**Comment by thuandt** [comment]
I upgraded to 16.04.
Without freetype patch, fonts is so ugly ...

**Comment by achaphiv** [comment]
I kicked off a new build using [bohoomil](https://github.com/bohoomil/fontconfig-ultimate)'s older 2.6.1 patch. Hopefully that works.

>  I has been used it more than year, but fontconfig-infinality config files is very old.
> @achaphiv can you update latest font config files for this repos?

Yeah, I've been meaning to do this. I have no idea how I originally created the original package though.

I've been lazy to update it since everything seems to work despite it being out of date. Additionally, it seems bohoomil completely replaces fontconfig. So now I have to patch that thing. Sigh, I'll eventually try to remake it.

 I really hate debian packaging.

**Comment by mikhailnov** [comment]
Thank you for your work despite hating debian packaging :)

**Comment by greatquux** [comment]
Yes I wanted to say I am very appreciative as well!! And as you saw the new package build worked and the old config files still work.  Thanks again!

**Comment by mikhailnov** [comment]
Why did you close the issue?

**Comment by Savemech** [comment]
guys any chance get this fancy working soon?

**Comment by thuandt** [comment]
@Savemech new build is online. It's not latest patch from bohoomil but it works.

**Comment by Savemech** [comment]
huh i mean for ubuntu 16.04 ppa's
mine box with these ppa's after installing fontconfig-infidality was broke something in way like:
cant click(app just hangs) anywhere but few windows

**Comment by thuandt** [comment]
It's work normally with my Ubuntu 16.04 box

**Comment by Savemech** [comment]
Thanks, then its looks like i have other kind issues with my box
