### ISSUE TITLE
Last update (freetype 2.7) broke hinting of "win98" style

### ISSUE THREAD

**Issue by volth** [achaphiv/ppa-fonts#29]
Now it looks like this (Ubuntu Mono w/o anti-aliasing):

![screenshot_2016-09-15_10-55-15](https://cloud.githubusercontent.com/assets/508305/18547474/148dd894-7b33-11e6-84de-68dffc211304.png)

This is how it was with freetype 2.6.1 (I still have it a docker container and I am looking a way how to downgrade libfreetype on the laptop):

![screenshot_2016-09-15_11-03-55](https://cloud.githubusercontent.com/assets/508305/18547719/640d331e-7b34-11e6-94f3-829899bc02e0.png)

PS. github blurs the images so you have to click to see them undistorted

**Comment by achaphiv** [comment]
I believe this can be fixed with `FREETYPE_PROPERTIES`.

# Version 40 (New default in freetype 2.7)
`export FREETYPE_PROPERTIES='truetype:interpreter-version=40'`
![interpreter-version-40](https://cloud.githubusercontent.com/assets/678337/18603929/3fb4c3ea-7c44-11e6-8756-b73cbedd6ea7.png)

# Version 35 (Old default in freetype 2.6)
`export FREETYPE_PROPERTIES='truetype:interpreter-version=45'`
![interpreter-version-35](https://cloud.githubusercontent.com/assets/678337/18603949/7522a470-7c44-11e6-9b23-afef424ce002.png)

**Comment by volth** [comment]
Why: for "win98" style on low-dpi screens.
Many fonts (especially those ttfs from windows) are much better without anti-aliasing, especially when they are 8-9px tall.

**Comment by achaphiv** [comment]
Gotcha.

Did the environment variable fix your problem?

**Comment by volth** [comment]
No, still weird.

![screenshot_2016-09-23_11-05-47](https://cloud.githubusercontent.com/assets/508305/18783847/d5ddd904-817d-11e6-8ecf-0d20a9a4b7f3.png)

Can you just restore .deb with freetype-2.6?
