### ISSUE TITLE
FreeType 2.9

### ISSUE THREAD

**Issue by kq01526** [achaphiv/ppa-fonts#36]
@achaphiv Can you please update the PPA to FreeType 2.8?

**Comment by kq01526** [comment]
Actually FreeType 2.8.1 is available now, which has some font rendering improvements:

https://www.freetype.org/index.html#news

**Comment by achaphiv** [comment]
Sure, I'll take a look at upgrading it.

**Comment by achaphiv** [comment]
I updated to 2.8.

I'm waiting on https://github.com/archfan/infinality_bundle to update for 2.8.1.

**Comment by kq01526** [comment]
Okay, thanks, asked for an update over there: https://github.com/archfan/infinality_bundle/issues/17

**Comment by kq01526** [comment]
FreeType 2.9 is available now:

https://www.freetype.org/index.html#news

**Comment by kq01526** [comment]
https://github.com/archfan/infinality_bundle/issues/17 still has not been solved.

**Comment by pandasauce** [comment]
Due to bugs in 2.8.1 that ships with Bionic I spent some time understanding @achaphiv's scripts and learning a bit about the technologies involved at the same time. While not quite a pull request because of my experiments, [this](https://gitlab.com/pandasauce/freetype-builds/tree/2.9.1-v38) will build FreeType 2.9.1 with v38 and all optional dependencies enabled. You only need to change the name and email address at line 91 in `workdir/pull-source` to correspond to your private key. You can generate your key by running `gpg2 --gen-key`.

Note that this hardcodes the key that upstream code is signed with, you may want to swap the comment status on lines 99 and 101 if you are not OK with that.

**Comment by pandasauce** [comment]
archfan/infinality_bundle#17 now has the patches fixed up for 2.9.1 compatibility.

**Comment by achaphiv** [comment]
Building 2.9.1 now.

Thanks for the heads up @pandasauce .

You also saved me a lot of time with the `--enable-freetype-config` hint. I now remember how much I hate debian packaging.

**Comment by achaphiv** [comment]
2.9.1 is built for bionic.
